### ISSUE TITLE
move the *.xml files into a separate folder

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/demonstrator#10]
right now it pollutes the top-level folder

**Comment by sbrunecker** [comment]
I don't know where the files are coming from. I didn't (intentionally) commit them.

**Comment by vonwenckstern** [comment]
Ok, then just remove the files from git again, please. Thank you.

 

Von: Stefan Brunecker [mailto:notifications@github.com] 
Gesendet: Mittwoch, 22. November 2017 00:50
An: EmbeddedMontiArc/demonstrator
Cc: Michael von Wenckstern; Author
Betreff: Re: [EmbeddedMontiArc/demonstrator] move the *.xml files into a separate folder (#10)

 

I don't know where the files are coming from. I didn't (intentionally) commit them.
