### ISSUE TITLE
Create 5 Lanes on Map

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/demonstrator#36]

**Comment by vonwenckstern** [comment]
Hi Michael,
I have added some division of sectors on the straight parts of the road. It would be harder to add it on the curved parts. Maybe we could start to work with it firstly? Check this concept, how it will work, and then later cover the whole track with more precise sectors grid and better picture.
Best wishes,
Ievgen Strepkov

![pic](https://user-images.githubusercontent.com/30497492/38381767-1cf22b54-3908-11e8-8e43-969c4db54e02.png)

**Comment by vonwenckstern** [comment]
@strepkov yes that is fine. First let's start with it and then improve the picture later. We just need a namming pattern, e.g. 02a - 02e, this is fine. Whereby `a` is most inner lane (small 4 in your picture) and `e` is most outer lane (small 0 in your picture)

**Comment by strepkov** [comment]
I Have already done with it:

zone2Coord.set("z00",[0,0]); // [x,y]
zone2Coord.set("z00e",[0,-6.5]);
zone2Coord.set("z00d",[0,-2.75]);
zone2Coord.set("z00c",[0,1]);
zone2Coord.set("z00b",[0,4.75]);
zone2Coord.set("z00a",[0,8.5]);

the first one like a most general position of the sector, and others locate position in the sector more precisely.

**Comment by vonwenckstern** [comment]
Ok, that's sounds good. We will look at the tickets next week, and then we will close them together.

**Comment by strepkov** [comment]
![test_track_cuted_numbers_lines5_letters](https://user-images.githubusercontent.com/25662834/38412398-93195718-3989-11e8-8a84-23872e085389.jpg)
