### ISSUE TITLE
Add Report View 1: Add Vectors above Map

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/demonstrator#37]
![image](https://user-images.githubusercontent.com/30497492/38355320-d3a725f8-38bc-11e8-893d-0075bc6c7e28.png)

* tail of vector: position of Car
* direction of vector: degree of car (not steering degree)
* length of vector: velocity of car

* use your JSON log file to draw the vector
* the user can say how often (every 10 ms, 100 ms) he want to have vector drawn

**Comment by strepkov** [comment]
I have done it partially. I looks like this.
![screenshot from 2018-04-08 21-44-11](https://user-images.githubusercontent.com/25662834/38471770-1319160e-3b76-11e8-87b1-82b6122914fb.png)

**Comment by strepkov** [comment]
And here the trajectory from typeScript controller. Easy to see the difference :)
![screenshot from 2018-04-10 10-21-41](https://user-images.githubusercontent.com/25662834/38545013-55c790f0-3ca9-11e8-94e0-7d18932635cb.png)
