### ISSUE TITLE
Save Simulation Data in a JSON File Format

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/demonstrator#38]
* `invent`  a good format so that you have all the data for reporting later
* save all the data every 10 ms

**Comment by strepkov** [comment]
I have created data structure:
{
	"Status": value,
	"Time": value,
	"Position": [value x,y],
	"Rotation": value,
	"Velocity": value,
	"Sensors": [distances from all sensors]
}

Now is possible after execution to download a .json file with all the telemetry data and analyze it separately.

**Comment by vonwenckstern** [comment]
@strepkov This is good, so we get a better seperation of concerns and much easier other analyzes can be added.

**Comment by strepkov** [comment]
I have updated demo: https://demo.embeddedmontiarc.com/selfdrivingcar/

**Comment by vonwenckstern** [comment]
Nice, but a `stop` button would be nice. So that I can stop it after half a round or what ever and then export the data.

I did not try to look if the data is reasonable; but we will see it if you finish #39 and #37
