### ISSUE TITLE
Add Report View 2: Car Position and Derivation

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/demonstrator#39]
![image](https://user-images.githubusercontent.com/30497492/38355692-ffe403ec-38bd-11e8-9b81-7dc9665961bb.png)

Just record the position of your TypeScript controller as the perfect lane, and then create the derivation from your EMA controller

**Comment by strepkov** [comment]
Michael, I have calculated the deviation in my case and for me it looks like something wrong with it. I have something like 65% here. I have calculated in each strep the distance between the ideal point and the point on current trajectory. Sum up all deviations and divide by the trajectory distance. (I have read it from this paper - Simulation Framework for Executing Component and Connector Models of Self-Driving Vehicles). 
![screenshot from 2018-04-10 17-04-06](https://user-images.githubusercontent.com/25662834/38565993-f2f8ac5e-3ce2-11e8-950b-980185ec4d0a.png)

**Comment by vonwenckstern** [comment]
@strepkov Yes 65% is too much. You need to take this formula to calculate the integral: https://de.wikipedia.org/wiki/Trapezregel

If the points of the typescript are `(tx1, ty1), (tx2, ty2), (tx3, ty3), ...` and the points for the EMA model are
`(ex1, ey1), (ex2, ey2), (ex3, ey3), ...` then you need to calculate the integral in the following way:
`Area1 = ||(tx2, ty2)-(tx1, ty1)|| * 0.5 * (||(ex1, ey1)-(tx1, ty1)|| + ||(ex2, ey2)-(tx2, ty2)||)`

`Area2 = ||(tx3, ty3)-(tx2, ty2)|| * 0.5 * (||(ex2, ey2)-(tx2, ty2)|| + ||(ex3, ey3)-(tx3, ty3)||)`
up to `AreaN`

And then you take the average:
`derivation = 1/n * (Area1 + Area2 + ... + AreaN)`

**Comment by strepkov** [comment]
With your formulas I have here the deviation 3,58... How do you think, it is fine?

**Comment by vonwenckstern** [comment]
@strepkov: it looks like that `3.5m²` could be the right integral area of the derivation when looking at the picture (regarding that you drove `725m`)
