### ISSUE TITLE
Add Model to master branch

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/demonstrator#42]
* Reporting scans all master branches at night

**Comment by strepkov** [comment]
The emam model was uploaded to demonstrator/gh-pages branch to be parsed at night :)

**Comment by strepkov** [comment]
Now it has been resolved and looks pretty nice :)
![screenshot from 2018-04-15 10-55-13](https://user-images.githubusercontent.com/25662834/38776715-af7c1a6c-409b-11e8-8754-14168a7e9370.png)

**Comment by vonwenckstern** [comment]
Yes, it looks pretty nice, but there is still a bug in the view (which is already reported at: https://github.com/EmbeddedMontiArc/visualisation/issues/12)

And your model passed all tests; nice job. The only thing you will not pass in future is the Stream-Test which @mh062909 will add soon. As you have not black-box tests for model. (You can translate your typescript tests to stream tests). Look at EMA-Studio how to run your stream tests. Best is you copy the `scripts/autopilot` folder, and adapt the paths -- everything should work unless executing it (but you could also hook up very easily your new Simulator).
