### ISSUE TITLE
Slider for Noise (0% to 100%)

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/demonstrator#44]

**Comment by strepkov** [comment]
I get rid from color buttons and added the slider, and it even works during runtime :)
![screenshot from 2018-04-15 11-00-48](https://user-images.githubusercontent.com/25662834/38776745-532fb1f0-409c-11e8-980d-aeb8808a2611.png)

**Comment by vonwenckstern** [comment]
@strepkov It looks nice, but I could not try it out -- as you did not update it at https://demo.embeddedmontiarc.com/selfdrivingcar/.

**Comment by strepkov** [comment]
It has been updated, now you can check it.

**Comment by vonwenckstern** [comment]
Yes it looks good, and we see that the controller does not work for noise over 40%
