### ISSUE TITLE
IDE

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/demonstrator#46]
Create an html file where you embedd the IDE with an iframe and an button above.
When you press at the button, show the text of the content you entered in the IDE.

For communication please ask @0xJMR.

**Comment by strepkov** [comment]
I have eventually figured out how to use VFS. Just found this docs : https://apidoc.c9.io/c9v3/#!/api/fs.
Now I can read files and extract content from them, and append files directly to VFS.
![screenshot from 2018-04-20 18-06-14](https://user-images.githubusercontent.com/25662834/39061925-2dcc5b9c-44c6-11e8-8c7f-08a5871e62f7.png)
From the right hand side you can see file names with content. Second output already with added file "testFile.emam" and content "some text".
