### ISSUE TITLE
Send content of IDE as ZIP-content (POST as base64 encoding) and return a ZIP file with JS + WASM

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/demonstrator#47]
the sending part should be stateless!

**Comment by strepkov** [comment]
@vonwenckstern , do you have some ideas which kind of server should work from the server side to receive files from  the online IDE and then send the generated files back? Thanks.

**Comment by vonwenckstern** [comment]
@strepkov just use anything like `Jetty` and receive it in a normal Java function, which then will unpack it.
Do not use Spring, Spring is overkill and too slow.

**Comment by vonwenckstern** [comment]
@strepkov Ok but then you are not too far away from compiling it on the server and send it back.

Please keep in mind, thatt he file where you extract it must be kind of unique since multiple users may use your tutorial at the same time; and since compiling needs some time it may overlap.

**Comment by vonwenckstern** [comment]
it should also support `folders` with hierarchy for packages

**Comment by strepkov** [comment]
In general everything is ready to use and the server part already deployed on the VM server and answer at requests. What is done :

1. read model files from onlineIDE environment
2. pack files to .zip
3. send it to the Jetty server(port 80)
4. extract files
5. save files on a disk
6. execute compiling process
7. pack compiled files into .zip (without base64, you mast not use it if you send file(blob))
8. send back with POST response
9. extract files in memory
10. save files in VFS folder

Only one question is left: how to include this files from VFS into simulator(.html). The using of static.html does not solve the problem(this links unaccessible from <script src=...></script>, it means I can not include it and use like normal file from file system).

**Comment by vonwenckstern** [comment]
@strepkov maybe you can make your server compliant to the WebAssemblyStudio https://github.com/wasdk/WebAssemblyStudio/issues/205#issuecomment-385667359 so that we can integrate our server into their tool

**Comment by strepkov** [comment]
I have managed to run the simulator with instantiating the .wasm object from memory but the solution has been done by editing the generated source code(.js). Still waiting for the better solution. (https://stackoverflow.com/questions/50150175/load-wasm-object-from-memory)

**Comment by strepkov** [comment]
It looks like I was able to solve the problem and have written the answer on the stackoverflow.https://stackoverflow.com/questions/50150175/load-wasm-object-from-memory
